<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zafu</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;r:(include|with|form|void|set|context|ignore)\b.*?&gt;			
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/r:(include|with|form|void|set|context|ignore)&gt;
		)</string>
	<key>keyEquivalent</key>
	<string>^~Z</string>
	<key>name</key>
	<string>Zafu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;r:ignore&gt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.zafu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/r:ignore&gt;</string>
			<key>name</key>
			<string>comment.block.zafu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>name</key>
			<string>comment.block.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ruby</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(//!).*$\n?</string>
			<key>name</key>
			<string>comment.line.zaffu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?r:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.zafu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.zafu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>name</key>
			<string>meta.tag.inline.render.zafu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>invalid.illegal.incomplete.html</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#zafu_stuffs</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>double_quoted_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zafu</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.zafu</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.zafu</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
							<key>name</key>
							<string>constant.character.escape.zafu</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>html_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre|a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.zafu</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.zafu</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((?: ?/)?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.zafu</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.inline.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#single_quoted_string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#double_quoted_string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(do|if|part|attr|test|mode|template|eval|with|link|include|blank|t|for)\b</string>
					<key>name</key>
					<string>keyword.control.zafu</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\$)\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?(e[+\-]?[0-9]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.zafu</string>
				</dict>
			</array>
		</dict>
		<key>single_quoted_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zafu</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.zafu</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.zafu</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
							<key>name</key>
							<string>constant.character.escape.zafu</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>zafu_stuffs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html_tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_quoted_string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.zafu</string>
	<key>uuid</key>
	<string>D2A8B261-C143-44CF-AB3C-5CCF56683A88</string>
</dict>
</plist>
